theme: jekyll-theme-slate
title: Rob Spectors ePortfolio
description: A Computer Science Professional
baseurl: /ePortFolio
pages_list:
  intro: '/home'
  Enhancement_1: '/enhancement_1.md'
  Enhancement_2: '/enhancement_2.md'
  Enhancement_3: '/enhancement_3.md'
  CodeReview: '/code_review.md'
  
